USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS THEMIS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS THEMIS_DB;
CREATE SCHEMA IF NOT EXISTS THEMIS_DB.PUBLIC;

USE WAREHOUSE THEMIS_WH;
USE DATABASE THEMIS_DB;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS CLEAN_DOCUMENTS (
  doc_id            STRING,
  project_id        STRING,
  created_at        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  source_hash       STRING,
  clean_hash        STRING,
  clean_text        STRING,
  page_count        NUMBER,
  approved_by       STRING,
  approval_time     TIMESTAMP_NTZ,
  retention_until   TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RISK_SUMMARY (
  doc_id                 STRING,
  scored_at              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  risk_score             NUMBER,
  risk_level             STRING,
  high_risk_clusters     NUMBER,
  total_clusters         NUMBER,
  quasi_identifier_count NUMBER,
  unresolved_count       NUMBER,
  notes                  STRING
);

CREATE TABLE IF NOT EXISTS REDACTION_EVENTS (
  doc_id                 STRING,
  event_time             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  entity_type            STRING,
  replacement_type       STRING,
  accepted               BOOLEAN,
  confidence             FLOAT,
  original_snippet_hash  STRING
);

CREATE ROLE IF NOT EXISTS THEMIS_APP_ROLE;

GRANT USAGE ON WAREHOUSE THEMIS_WH TO ROLE THEMIS_APP_ROLE;
GRANT USAGE ON DATABASE THEMIS_DB TO ROLE THEMIS_APP_ROLE;
GRANT USAGE ON SCHEMA THEMIS_DB.PUBLIC TO ROLE THEMIS_APP_ROLE;

GRANT SELECT, INSERT ON TABLE THEMIS_DB.PUBLIC.CLEAN_DOCUMENTS  TO ROLE THEMIS_APP_ROLE;
GRANT SELECT, INSERT ON TABLE THEMIS_DB.PUBLIC.RISK_SUMMARY     TO ROLE THEMIS_APP_ROLE;
GRANT SELECT, INSERT ON TABLE THEMIS_DB.PUBLIC.REDACTION_EVENTS TO ROLE THEMIS_APP_ROLE;

CREATE USER IF NOT EXISTS THEMIS_APP_USER
  PASSWORD = 'INNOVATEHER2026THEMISPROJECT'
  DEFAULT_ROLE = THEMIS_APP_ROLE
  DEFAULT_WAREHOUSE = THEMIS_WH
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE THEMIS_APP_ROLE TO USER THEMIS_APP_USER;
